### ISSUE TITLE
Could not install the plugin

### ISSUE THREAD

**Issue by ghost** [Agies/MVVMCross.Plugins.Validation#1]
HI,

I tried to install the plugin from nuget and it failed. I am using VS2013 Update 2 on windows 8.1. I have previously installed the following plugins

mvvmcross
mvvmcross messenger
mvvmcross Sqlite Plugin (OLD VERSION)

When I tried to install the validation plugin I go the following message.

Is there a fix or a workaround for this?

Attempting to resolve dependency 'MvvmCross.HotTuna.CrossCore (≥ 3.0.13)'.
Attempting to resolve dependency 'MvvmCross.PortableSupport (≥ 3.2.1)'.
Attempting to resolve dependency 'MvvmCross.HotTuna.Plugin.Messenger (≥ 3.0.13)'.
Attempting to resolve dependency 'MvvmCross (≥ 3.1.1)'.
Attempting to resolve dependency 'MvvmCross.HotTuna.StarterPack (≥ 3.2.1)'.
Attempting to resolve dependency 'MvvmCross.HotTuna.MvvmCrossLibraries (≥ 3.2.1)'.
Installing 'MVVMCross.Plugins.Validation 1.0.2'.
Successfully installed 'MVVMCross.Plugins.Validation 1.0.2'.
Adding 'MVVMCross.Plugins.Validation 1.0.2' to MySecondXamApp.Core.
Uninstalling 'MVVMCross.Plugins.Validation 1.0.2'.
Successfully uninstalled 'MVVMCross.Plugins.Validation 1.0.2'.
Install failed. Rolling back...
Could not install package 'MVVMCross.Plugins.Validation 1.0.2'. You are trying to install this package into a project that targets 'portable-net45+win+wpa81+MonoAndroid10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by ZhangZihe** [comment]
Pease try it again.
