### ISSUE TITLE
Nuget packages should be built in release mode

### ISSUE THREAD

**Issue by ilkayilknur** [Agies/MVVMCross.Plugins.Validation#13]
Hi,
We're using **MvvmCross.Plugins.Validation** and **MVVMCross.Plugins.Validation.ForFieldBinding** nuget packages in our portable class library project.
We submitted our UWP app to windows store, but the app was rejected because of the reason below. 

**_"The binary MVVMCross.Plugins.Validation.dll is built in debug mode."_**

You can find the package definitions below.

```
<package id="MVVMCross.Plugins.Validation" version="2.0.0" targetFramework="portable45-net45+win8" />
<package id="MVVMCross.Plugins.Validation.ForFieldBinding" version="2.0.0" targetFramework="portable45-net45+win8" />
```

File references in nuspec files should point to release folder.

**Comment by ZhangZihe** [comment]
Sorry for the error, We have built in release mode. Please update your packages. Thanks

**Comment by ilkayilknur** [comment]
Thanks for the quick response @ZhangZihe .
