### ISSUE TITLE
Is ther any sample ?

### ISSUE THREAD

**Issue by dearsherlock** [Agies/MVVMCross.Plugins.Validation#2]
The plugins looks greate! Please give us simple demo project for the plugins,thanks.Is it support mvvm v3.5?

**Comment by ghost** [comment]
@dearsherlock Did you get an answer to this/ manage to work it out? I'm attempting to use it now in 3.5.

**Comment by jamsoft** [comment]
I've just looked at this and demo is not a demo of anything as far as I can tell.  Very odd.

**Comment by dazinator** [comment]
+1 for some demo / sample please!

**Comment by ZhangZihe** [comment]
Hellow everyone, there is a demo here: 
https://github.com/Agies/MVVMCross.Plugins.Validation/tree/master/MVVMCross.Plugins.Validation.Demo
