### ISSUE TITLE
Failed to resolve parameter for parameter validator of type IValidator

### ISSUE THREAD

**Issue by senpark15** [Agies/MVVMCross.Plugins.Validation#9]
I have installed plugin from nuget. I tried to setup validation on activity OnCreate. but throws error in  Mvx.Resolve<IMvxValidationService>();

this is my code:
 private IMvxValidationService _validationService;
 _validationService = Mvx.Resolve<IMvxValidationService>();
 _validationService.SetupForValidation(this.BindingContext, this.ViewModel);

error:
MvvmCross.Platform.Exceptions.MvxIoCResolveException: Failed to resolve parameter for parameter validator of type IValidator when creating MVVMCross.Plugins.Validation.Droid.MvxAndroidValidationService

**Comment by ZhangZihe** [comment]
The implementation of IMvxValidationService has not construction without parameter. Such as:

```
public MvxAndroidValidationService(IValidator validator, IMvxMessenger messenger)
            : base(validator, messenger)
 {

 }
```

```
public MvxTouchValidationService(IMvxToastService toastService, IValidator validator, IMvxMessenger messenger)
            : base(validator, messenger)
{
        this.toastService = toastService;
}
```

So,  The IMvxValidationService  can not be resolve immediately.
However, you can use 'ValidatingViewModel ', reference: http://agiescode.ghost.io/2014/05/10/mobile-project-one/
or use the 'IValidator', it is my recommendation. eg:

```
var errors = Mvx.Resolve<IValidator>().Validate(ViewModel);
 if (!errors.IsValid)
{
       //TODO: You can display the errors there.
       return;
}
```

Of course, you must do RegistType in 'APP.cs':

```
public class App : MvvmCross.Core.ViewModels.MvxApplication
    {
        public override void Initialize()
        {
            CreatableTypes()
                .EndingWith("Service")
                .AsInterfaces()
                .RegisterAsLazySingleton();

            Mvx.RegisterType<IValidator, Validator>();  //*

            RegisterAppStart<ViewModels.FirstViewModel>();
        }
    }
```

I hope this can help you. Good luck.
